library(KoNLP) # 자연어 분석 패키지 로드
library(stringr) # 문자 처리 패키지 로드
library(dplyr) # 전처리 패키지 로드
library(RColorBrewer) # 글자 색깔 패키지 로드
library(wordcloud2) # 워드 클라우드2 패키지 로드
useNIADic() # 사전 설정

mergeUserDic(data.frame(c("넵"), c("ncn")))
mergeUserDic(data.frame(c("G-CA"), c("ncn")))
mergeUserDic(data.frame(c("코로나19"), c("ncn")))
mergeUserDic(data.frame(c("유증상자"), c("ncn")))
mergeUserDic(data.frame(c("자택격리자"), c("ncn")))
mergeUserDic(data.frame(c("FAM"), c("ncn")))
mergeUserDic(data.frame(c("비모수"), c("ncn")))
mergeUserDic(data.frame(c("팸인원"), c("ncn")))
mergeUserDic(data.frame(c("업로드"), c("ncn")))
mergeUserDic(data.frame(c("slc"), c("ncn")))
mergeUserDic(data.frame(c("조교쌤"), c("ncn")))
mergeUserDic(data.frame(c("e참뜰"), c("ncn")))
mergeUserDic(data.frame(c("해인자"), c("ncn")))
mergeUserDic(data.frame(c("토익"), c("ncn")))
mergeUserDic(data.frame(c("컴활"), c("ncn")))
mergeUserDic(data.frame(c("e스포츠"), c("ncn")))
mergeUserDic(data.frame(c("라온"), c("ncn")))
mergeUserDic(data.frame(c("늘봄"), c("ncn")))
mergeUserDic(data.frame(c("카톡"), c("ncn")))
mergeUserDic(data.frame(c("생협쿠폰"), c("ncn")))
mergeUserDic(data.frame(c("확산"), c("ncn")))
mergeUserDic(data.frame(c("코로나"), c("ncn")))
mergeUserDic(data.frame(c("통개학개론"), c("ncn")))
mergeUserDic(data.frame(c("분포론"), c("ncn")))
mergeUserDic(data.frame(c("학업코칭"), c("ncn")))
mergeUserDic(data.frame(c("갠톡"), c("ncn")))
mergeUserDic(data.frame(c("동행"), c("ncn")))
mergeUserDic(data.frame(c("멘토"), c("ncn")))
mergeUserDic(data.frame(c("계절학기"), c("ncn")))
mergeUserDic(data.frame(c("과대"), c("ncn")))
mergeUserDic(data.frame(c("부과대"), c("ncn")))
mergeUserDic(data.frame(c("특별학점"), c("ncn")))
mergeUserDic(data.frame(c("실험계획법"), c("ncn")))
mergeUserDic(data.frame(c("페이스북"), c("ncn")))
mergeUserDic(data.frame(c("학우"), c("ncn")))
mergeUserDic(data.frame(c("수강신청"), c("ncn")))
mergeUserDic(data.frame(c("장바구니제"), c("ncn")))
mergeUserDic(data.frame(c("네"), c("ncn")))
mergeUserDic(data.frame(c("총학생회"), c("ncn")))
mergeUserDic(data.frame(c("동행"), c("ncn")))
mergeUserDic(data.frame(c("라온"), c("ncn")))
mergeUserDic(data.frame(c("단기어학연수"), c("ncn")))
mergeUserDic(data.frame(c("2020"), c("ncn")))
mergeUserDic(data.frame(c("hwp"), c("ncn")))
mergeUserDic(data.frame(c("pdf"), c("ncn")))
mergeUserDic(data.frame(c("동계계절학기"), c("ncn")))
mergeUserDic(data.frame(c("동계"), c("ncn")))
mergeUserDic(data.frame(c("하계"), c("ncn")))
mergeUserDic(data.frame(c("하계계절학기"), c("ncn")))
mergeUserDic(data.frame(c("계절학기"), c("ncn")))
mergeUserDic(data.frame(c("학과 특성화 장학금"), c("ncn")))
mergeUserDic(data.frame(c("선형대수학"), c("ncn")))
mergeUserDic(data.frame(c("강릉원주대학교"), c("ncn")))
mergeUserDic(data.frame(c("국립강릉원주대학교"), c("ncn")))
mergeUserDic(data.frame(c("복수전공"), c("ncn")))
mergeUserDic(data.frame(c("복학"), c("ncn")))
mergeUserDic(data.frame(c("휴학"), c("ncn")))
mergeUserDic(data.frame(c("학습법"), c("ncn")))
mergeUserDic(data.frame(c("3학년"), c("ncn")))
mergeUserDic(data.frame(c("4학년"), c("ncn")))
mergeUserDic(data.frame(c("여름계절학기"), c("ncn")))
mergeUserDic(data.frame(c("14학번"), c("ncn")))
mergeUserDic(data.frame(c("16학번"), c("ncn")))
mergeUserDic(data.frame(c("17학번"), c("ncn")))
mergeUserDic(data.frame(c("18학번"), c("ncn")))
mergeUserDic(data.frame(c("품질관리"), c("ncn")))
mergeUserDic(data.frame(c("등록금"), c("ncn")))
mergeUserDic(data.frame(c("추가"), c("ncn")))
mergeUserDic(data.frame(c("납부"), c("ncn")))
mergeUserDic(data.frame(c("멘토링"), c("ncn")))
mergeUserDic(data.frame(c("정보통계학과"), c("ncn")))
mergeUserDic(data.frame(c("학회장"), c("ncn")))
mergeUserDic(data.frame(c("톡게시판"), c("ncn")))
mergeUserDic(data.frame(c("롤"), c("ncn")))
mergeUserDic(data.frame(c("201호"), c("ncn")))
mergeUserDic(data.frame(c("연습문제"), c("ncn")))
mergeUserDic(data.frame(c("기말고사"), c("ncn")))
mergeUserDic(data.frame(c("중간고사"), c("ncn")))
mergeUserDic(data.frame(c("단일후보"), c("ncn")))
mergeUserDic(data.frame(c("차기학회장"), c("ncn")))
mergeUserDic(data.frame(c("파일"), c("ncn")))
mergeUserDic(data.frame(c("근로 장학금"), c("ncn")))
mergeUserDic(data.frame(c("국가장학금"), c("ncn")))
mergeUserDic(data.frame(c("자연대"), c("ncn")))
mergeUserDic(data.frame(c("여러분"), c("ncn")))
mergeUserDic(data.frame(c("실험계획"), c("ncn")))
mergeUserDic(data.frame(c("궁금한"), c("ncn")))
mergeUserDic(data.frame(c("특별학점"), c("ncn")))
mergeUserDic(data.frame(c("2학기"), c("ncn")))
mergeUserDic(data.frame(c("배움모둠"), c("ncn")))
mergeUserDic(data.frame(c("차기학회장"), c("ncn")))
mergeUserDic(data.frame(c("강릉"), c("ncn")))
mergeUserDic(data.frame(c("체크"), c("ncn")))
mergeUserDic(data.frame(c("빨리"), c("ncn")))
mergeUserDic(data.frame(c("미리미리"), c("ncn")))
mergeUserDic(data.frame(c("승인절차"), c("ncn")))
mergeUserDic(data.frame(c("이수증"), c("ncn")))
mergeUserDic(data.frame(c("안전교육"), c("ncn")))
mergeUserDic(data.frame(c("입학본부"), c("ncn")))
mergeUserDic(data.frame(c("공약설명회"), c("ncn")))
mergeUserDic(data.frame(c("질의응답"), c("ncn")))
mergeUserDic(data.frame(c("일일이"), c("ncn")))
mergeUserDic(data.frame(c("영상재생"), c("ncn")))
mergeUserDic(data.frame(c("오류"), c("ncn")))



# 데이터 불러오기
text1 <- readLines("text2.txt")
text1

# 명사 추출
text2 <- extractNoun(text1)
text2

# List 형태 해제
text3 <- unlist(text2)
text3

# 불용어 처리
text4<-gsub("책보", " " ,text3)
text5<-gsub("고싶", " " ,text4)
text6<-gsub("은사", " " ,text5)
text7<-gsub("장하", " " ,text6)
text8<-gsub("해서", " " ,text7)
text9<-gsub("4", " " ,text8)
text10<-gsub("3", " " ,text9)
text11<-gsub("자기", " " ,text10)
text12<-gsub("소개", " " ,text11)
text13<-gsub("hw", " " ,text12)
text14<-gsub("p", " " ,text13)
text15<-gsub("준성", " " ,text14)
text16<-gsub("김동기", " " ,text15)
text17<-gsub("조교", "조교" ,text16)
text18<-gsub("삭제", " " ,text17)
text19<-gsub("사진", " " ,text18)
text20<-gsub("주면", " " ,text19)
text21<-gsub("한점2", " " ,text20)
text22<-gsub("1", " " ,text21)
text23<-gsub("이모", " " ,text22)
text24<-gsub("f", " " ,text23)
text25<-gsub("개시\\W체인지", " " ,text24)
text26<-gsub("김영", " " ,text25)
text27<-gsub("안하", " " ,text26)
text28<-gsub("신분", " " ,text27)
text29<-gsub("G", " " ,text28)
text30<-gsub("홍성", " " ,text29)
text31<-gsub("도빨리해주세", " " ,text30)
text32<-gsub("'동행'입니다!", " " ,text31)
text33<-gsub("경우", " " ,text32)
text34<-gsub("10", " " ,text33)
text35<-gsub("5", " " ,text34)
text36<-gsub("감사하겠습니", " " ,text35)
text37<-gsub("꼭해주세", " " ,text36)
text38<-gsub("7장과제", " " ,text37)
text39<-gsub("저번", " " ,text38)
text40<-gsub("한점", " " ,text39)
text41<-gsub("7주차", " " ,text40)
text42<-gsub("수정\\W중간", " " ,text41)
text43<-gsub("오전8시30분부터", " " ,text42)
text44<-gsub("여는거", " " ,text43)
text45<-gsub("있습니", " " ,text44)
text46<-gsub("쌤", "조교",text45)
text47<-gsub("조교샘", "조교", text46)
text48<-gsub("이후", " " ,text47)
text49<-gsub("기말","기말고사",text48)
text50<-gsub("중간", "중간고사",text49)
text51<-gsub("오후9시까지는", " " ,text50)
text52<-gsub("하기", " " ,text51)
text53<-gsub("정기", " " ,text52)
text54<-gsub("24", " " ,text53)
text55<-gsub("17.", " " ,text54)
text56<-gsub("들입", " " ,text55)
text57<-gsub("동연", " " ,text56)
text58<-gsub("텐트", " " ,text57)
text59<-gsub("준성", " " ,text58)
text60<-gsub("음주", " " ,text59)
text61<-gsub("(붙임1)2020학년도", " " ,text60)
text62<-gsub("주시", " " ,text61)
text63<-gsub("하기", " " ,text62)
text64<-gsub("특별학점\\W토익", " " ,text63)
text65<-gsub("8", " " ,text64)
text66<-gsub("35", " " ,text65)
text67<-gsub("19", " " ,text66)
text68<-gsub("만나뵙", " " ,text67)
text69<-gsub("때문", " " ,text68)
text70<-gsub("한거", " " ,text69)
text71<-gsub("8월14일(금)", " " ,text70)
text72<-gsub("14", " " ,text71)
text73<-gsub("안녕하십니까", " " ,text72)
text74<-gsub("때문", " " ,text73)
text75<-gsub("7주차", " " ,text74)
text76<-gsub("14", " " ,text75)
text77<-gsub("10", " " ,text76)
text78<-gsub("이번", " " ,text77)
text79<-gsub("해주시", " " ,text78)
text80<-gsub("CA", " " ,text79)
text81<-gsub("개론", " " ,text80)
text82<-gsub("갠톡으로", "갠톡",text81)
text83<-gsub("있습니", " " ,text82)
text84<-gsub("관련하", " " ,text83)
text85<-gsub("여는거", " " ,text84)
text86<-gsub("라온입니", "라온",text85)
text87<-gsub("때문", " " ,text86)
text88<-gsub("꼭해주세", " " ,text87)
text89<-gsub("17.", " " ,text88)
text90<-gsub("만나뵙", " " ,text89)
text91<-gsub("해주", " " ,text90)
text92<-gsub("안녕", " ",text91)
text93<-gsub("하신", " ",text92)
text94<-gsub("해보", " ",text93)
text95<-gsub("6", " ",text94)
text96<-gsub("9", " ",text95)
text97<-gsub("d", " ",text96)
text98<-gsub("하세", " ",text97)
text99<-gsub("하시", " ",text98)
text100<-gsub("하면", " ",text99)
text101<-gsub("해하", " ",text100)
text102<-gsub("7학번", "17학번",text101)
text103<-gsub("약간", " ",text102)
text104<-gsub("조교조교", "조교",text103)
text105<-gsub("0", " ",text104)
text106<-gsub("202", " ",text105)
text107<-gsub("2020", "",text106)
text108<-gsub("부조", "",text107)
text109<-gsub("제 대", "",text108)
text110<-gsub("품질", "품질관리",text109)
text111<-gsub("사다리", "사다리타기",text110)
text112<-gsub("타기", "사다리타기",text111)
text113<-gsub("사다리타기사다리타기", "사다리타기",text112)
text114<-gsub("2 2", "",text113)
text115<-gsub("해", "",text114)
text116<-gsub("라온다", "라온",text115)


# 글자수 한정
text117 <- text116[nchar(text116) < 5]
text117 <- text117[nchar(text117) > 1]

# 내림차순 정렬
text118 <- sort(table(text117), decreasing = T)

# 상위 60개 단어 추출
text119 <- head(text118, 60)
text119

# 빈도 그래프 작성
library(ggplot2) # ggplot2 패키지 로드
library(dplyr) # dplyr 패키지 로드
df <- as.data.frame(text119) 
df <- rename(df,
             word = text117)
ggplot(data = df, aes(x = reorder(word, Freq), y = Freq)) +
  geom_col() +
  coord_flip()

set.seed(1234) # 난수 설정
pal <- brewer.pal(9, "Blues")[5:9] # 색 선정

# 워드 클라우드 작성
wordcloud2(text119, size = 0.7, fontFamily = "Tmon몬소리", color = pal)

getwd()

           